### ISSUE TITLE
Should still work?

### ISSUE THREAD

**Issue by jorgb90** [aashan10/magento2-link-guest-order#4]
Few years further now, should this still be compatible?

**Comment by rachanajay** [comment]
Mostly yes, although filtering guest order data in admin grid doesn't work anymore.

**Comment by sumeetmagento** [comment]
it is not working with Filter,any code to fixing this ?

**Comment by rachanajay** [comment]
Yes, I have fixed it.
I'll try to send the pr for the code changes soon  @sumeetmagento

**Comment by sumeetmagento** [comment]
@rachanajay is it possible now?
or you will just share code here

**Comment by rajkumargwl** [comment]
@rachanajay any update please ?

**Comment by sumeetmagento** [comment]
@rachanajay 
any update please ?

We are getting this issue when we filter via order id - 
`main.CRITICAL: PDOException: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'increment_id' in where clause is ambiguous in /vendor/magento/framework/DB/Statement/Pdo/Mysql.php:90`

**Comment by aashan10** [comment]
@sumeetmagento @rachanajay Thank you for using this project. I used to work with magento a while back and I created this for my own use case, but lately I haven't been using it so much. I'll try to update this to support the latest magento 2 version when I have time and if you already have worked on this, feel free to send a pull request. Sorry for the delayed response.

**Comment by aashan10** [comment]
@jorgb90 To be honest here, I didn't know anyone else was using this module. I created it a while back when I was still working on Magento 2. I even missed the notification for this issue among a thousand github spam emails I guess. But if you guys are actively using it, I'd be happy to keep this project running. I'll update it when I have time, probably over the weekend sometimes.

**Comment by aashan10** [comment]
Also, it'd be really helpful for me to work on it if someone could open up a new issue mentioning the exact problem. This issue feels more like a discussion than an issue that I could get some information on. Please include steps to reproduce the mentioned problem with filters.

@sumeetmagento maybe you could do that?

**Comment by aashan10** [comment]
NVM, I found the issue myself and updated the package.
https://github.com/aashan10/magento2-link-guest-order/commit/f959322df7c669872a058c5f6971d926441945ba

@sumeetmagento I've published a new release with this bugfix which should solve your problem. Please update the version to `1.0.5` in your composer.json
